stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - data/RestaurantReviews.tsv
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/RestaurantReviews.tsv
    - src/preprocess.py
    outs:
    - data/preprocessed_data.joblib
  train:
    cmd: python src/train.py
    deps:
    - data/preprocessed_data.joblib
    - src/train.py
    outs:
    - models/model.joblib
    - data/test_data.joblib
  evaluate:
    cmd: python src/evaluation.py
    deps:
    - data/test_data.joblib
    - models/model.joblib
    - src/evaluation.py
    metrics:
    - metrics/metrics.json
