stages:
  get_data:
    cmd: python src/data/get_data.py
    deps:
    - src/data/get_data.py
    outs:
    - data/raw/RestaurantReviews.tsv
  preprocess:
    cmd: python src/features/preprocess.py
    deps:
    - data/raw/RestaurantReviews.tsv
    - src/features/preprocess.py
    outs:
    - data/processed/preprocessed_data.joblib
  train:
    cmd: python src/models/train.py
    deps:
    - data/processed/preprocessed_data.joblib
    - src/models/train.py
    outs:
    - models/model.joblib
    - data/test/test_data.joblib
  evaluate:
    cmd: python src/models/evaluation.py
    deps:
    - data/test/test_data.joblib
    - models/model.joblib
    - src/models/evaluation.py
    metrics:
    - metrics/metrics.json
